"""Modelling: baseline strategies and the metrics that judge them."""

from gridiron.modeling.baselines import (
    BASELINES,
    DEFAULT_SEED,
    BaselineError,
    eligible_games,
    epa_fallback_count,
    predict_away_every_game,
    predict_better_epa,
    predict_favorite,
    predict_home_every_game,
    predict_random,
    predict_underdog,
)
from gridiron.modeling.metrics import (
    BREAK_EVEN_ACCURACY,
    STANDARD_PRICE,
    WIN_PROFIT,
    MetricError,
    accuracy,
    comparison_table,
    evaluate,
    max_drawdown,
    profit_curve,
    roi,
    season_accuracy,
    season_table,
    wins_and_losses,
)

__all__ = [
    "BASELINES",
    "BREAK_EVEN_ACCURACY",
    "DEFAULT_SEED",
    "STANDARD_PRICE",
    "WIN_PROFIT",
    "BaselineError",
    "MetricError",
    "accuracy",
    "comparison_table",
    "eligible_games",
    "epa_fallback_count",
    "evaluate",
    "max_drawdown",
    "predict_away_every_game",
    "predict_better_epa",
    "predict_favorite",
    "predict_home_every_game",
    "predict_random",
    "predict_underdog",
    "profit_curve",
    "roi",
    "season_accuracy",
    "season_table",
    "wins_and_losses",
]
